{
"id": "ch_3MnwmPQV2uO6Z0J11RKpPERR",
"object": "charge",
"amount": 10000,
"amount_captured": 10000,
"amount_refunded": 0,
"application": "ca_NYjfTKxKaopFrrieREauAt6EmRukySMT",
"application_fee": null,
"application_fee_amount": null,
"balance_transaction": "txn_3MnwmPQV2uO6Z0J1150WFWJl",
"billing_details": {
"address": {
"city": null,
"country": null,
"line1": null,
"line2": null,
"postal_code": "42424",
"state": null
},
"email": null,
"name": null,
"phone": null
},
"calculated_statement_descriptor": "ITECOUNSEL.COM",
"captured": true,
"created": 1679372797,
"currency": "aud",
"customer": null,
"description": "This is test payment",
"destination": null,
"dispute": null,
"disputed": false,
"failure_balance_transaction": null,
"failure_code": null,
"failure_message": null,
"fraud_details": [],
"invoice": null,
"livemode": false,
"metadata": [],
"on_behalf_of": null,
"order": null,
"outcome": {
"network_status": "approved_by_network",
"reason": null,
"risk_level": "normal",
"risk_score": 42,
"seller_message": "Payment complete.",
"type": "authorized"
},
"paid": true,
"payment_intent": null,
"payment_method": "card_1MnwmPQV2uO6Z0J1XOB1q3ka",
"payment_method_details": {
"card": {
"brand": "visa",
"checks": {
"address_line1_check": null,
"address_postal_code_check": "pass",
"cvc_check": "pass"
},
"country": "US",
"exp_month": 4,
"exp_year": 2024,
"fingerprint": "OrjegQ1DQEtYLCo2",
"funding": "credit",
"installments": null,
"last4": "4242",
"mandate": null,
"network": "visa",
"three_d_secure": null,
"wallet": null
},
"type": "card"
},
"receipt_email": null,
"receipt_number": null,
"receipt_url": "https:\/\/pay.stripe.com\/receipts\/payment\/CAcaFwoVYWNjdF8xTW52TkJRVjJ1TzZaMEoxKP3j5KAGMgbf3kRbr3I6LBYGaThok0tJwfNSno7AZ1rl3iAQv0XVmCQ5D2qNPek107gKY9SvB5rMaXtn",
"refunded": false,
"review": null,
"shipping": null,
"source": {
"id": "card_1MnwmPQV2uO6Z0J1XOB1q3ka",
"object": "card",
"address_city": null,
"address_country": null,
"address_line1": null,
"address_line1_check": null,
"address_line2": null,
"address_state": null,
"address_zip": "42424",
"address_zip_check": "pass",
"brand": "Visa",
"country": "US",
"customer": null,
"cvc_check": "pass",
"dynamic_last4": null,
"exp_month": 4,
"exp_year": 2024,
"fingerprint": "OrjegQ1DQEtYLCo2",
"funding": "credit",
"last4": "4242",
"metadata": [],
"name": null,
"tokenization_method": null
},
"source_transfer": null,
"statement_descriptor": null,
"statement_descriptor_suffix": null,
"status": "succeeded",
"transfer_data": null,
"transfer_group": null
}