{
"id": "ch_3MnFcMQhHfdpdP56129mqinT",
"object": "charge",
"amount": 10000,
"amount_captured": 10000,
"amount_refunded":company 0,
"application": "ca_NWg8x2hjPQivK1Rnf1vVmOJYdZ6X8udy",
"application_fee": null,
"application_fee_amount": null,
"balance_transaction": "txn_3MnFcMQhHfdpdP561F6DzR27",
"billing_details": {
"address": {
"city": null,
"country": null,
"line1": null,
"line2": null,
"postal_code": "42424",
"state": null
},
"email": null,
"name": null,
"phone": null
},
"calculated_statement_descriptor": "QUADQUE.TECH",
"captured": true,
"created": 1679206882,
"currency": "aud",
"customer": null,
"description": "This is test payment",
"destination": null,
"dispute": null,
"disputed": false,
"failure_balance_transaction": null,
"failure_code": null,
"failure_message": null,
"fraud_details": [],
"invoice": null,
"livemode": false,
"metadata": [],
"on_behalf_of": null,
"order": null,
"outcome": {
"network_status": "approved_by_network",
"reason": null,
"risk_level": "normal",
"risk_score": 16,
"seller_message": "Payment complete.",
"type": "authorized"
},
"paid": true,
"payment_intent": null,
"payment_method": "card_1MnFcMQhHfdpdP56ZLtWGC8f",
"payment_method_details": {
"card": {
"brand": "visa",
"checks": {
"address_line1_check": null,
"address_postal_code_check": "pass",
"cvc_check": "pass"
},
"country": "US",
"exp_month": 4,
"exp_year": 2024,
"fingerprint": "59RFOaCRdIoMR9Bb",
"funding": "credit",
"installments": null,
"last4": "4242",
"mandate": null,
"network": "visa",
"three_d_secure": null,
"wallet": null
},
"type": "card"
},
"receipt_email": null,
"receipt_number": null,
"receipt_url": "https:\/\/pay.stripe.com\/receipts\/payment\/CAcaFwoVYWNjdF8xTWxjc0NRaEhmZHBkUDU2KOLT2qAGMgYDswUm2lc6LBbD-fymYULOztyiFB0LhiER_xkWGabAXhlvTfzD1HheFshM2NHNq5N4owLx",
"refunded": false,
"refunds": {
"object": "list",
"data": [],
"has_more": false,
"total_count": 0,
"url": "\/v1\/charges\/ch_3MnFcMQhHfdpdP56129mqinT\/refunds"
},
"review": null,
"shipping": null,
"source": {
"id": "card_1MnFcMQhHfdpdP56ZLtWGC8f",
"object": "card",
"address_city": null,
"address_country": null,
"address_line1": null,
"address_line1_check": null,
"address_line2": null,
"address_state": null,
"address_zip": "42424",
"address_zip_check": "pass",
"brand": "Visa",
"country": "US",
"customer": null,
"cvc_check": null,
"dynamic_last4": null,
"exp_month": 4,
"exp_year": 2024,
"fingerprint": "59RFOaCRdIoMR9Bb",
"funding": "credit",
"last4": "4242",
"metadata": [],
"name": null,
"tokenization_method": null
},
"source_transfer": null,
"statement_descriptor": null,
"statement_descriptor_suffix": null,
"status": "succeeded",
"transfer_data": null,
"transfer_group": null
}